# -*- coding: utf-8 -*-
"""Организация программ и методы строк

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s809SOgOEzY0KUH-ofZSt5iV2RlRqeUD
"""

my_string = input('Write here some text: ')

print(len(my_string))

print(my_string.upper())

print(my_string.lower())

print(my_string.replace(' ', ''))

print(my_string[0])

print(my_string[-1])